# inherit_from: .rubocop_todo.yml

# 50音順にならべること

AllCops:
  UseCache: true
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/*.rb'
  Exclude:
    - '**/*.tab.rb' # Raccの出力ファイル
    - '**/*_pb.rb' # protocの出力ファイル

# heredoc のスタイルを <<~ に統一
Layout/IndentHeredoc:
  EnforcedStyle: squiggly

# Rakefile のファイル名は例外
Naming/FileName:
  Exclude:
    - '**/Rakefile'
    - '**/Gemfile'

# 日本語コメントを禁止しない
Style/AsciiComments:
  Enabled: false

# 下記変換をやめる（インデントが統一しにくいため）
# if x
#   a = 1
# else
#   a = 2
# end
# =>
# a = if x
#       1
#     else
#       2
#     end
Style/ConditionalAssignment:
  Enabled: false

# Rakefile は 古いHashスタイルのほうが自然なので、排除
Style/HashSyntax:
  Exclude:
    - '**/*.rake'
    - '**/Rakefile'

# ブロックの長さ制限
Metrics/BlockLength:
  Max: 80
  
# クラスの長さ制限
Metrics/ClassLength:
  Max: 1000
  
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 120

# メソッドの長さ制限
Metrics/MethodLength:
  Max: 80

# モジュールの長さ制限
Metrics/ModuleLength:
  Max: 1000

# $! => $ERROR_INFO を強制しない(require 'English'が必要なため)
Style/SpecialGlobalVars:
  Enabled: false

# Offense count: 1
#Metrics/AbcSize:
#  Max: 104

# Offense count: 2
Metrics/CyclomaticComplexity:
  Max: 31

# Offense count: 2
#Metrics/PerceivedComplexity:
#  Max: 31

# Offense count: 1
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

